services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    environment:
      - REDIS_PASSWORD=admin # should be somewhere else
    ports:
      - "6379:6379"
