services:
  app:
    build:
      context: .  # Assumes you have a Dockerfile in the same directory
    env_file:
      - .env  # Environment variables for Express server
    ports:
      - "8080:8080"  # Map the Express server port to localhost
    depends_on:
      - redis  # Ensures Redis starts before the Express app

  redis:
    image: "redis:latest"
    env_file:
      - .env  # Environment variables for Redis server
    ports:
      - "6379:6379"  # Map the Redis port to localhost